= Структура проекта

[source,text]
----
.
├── doc
│   └── asciidoc
├── lst
├── sdc
├── rtl
├── syn
│   └── files
│   └── out
│   └── scripts
│   └── work_genus
│   └── config.mk
│   └── Makefile
└── Makefile
----

* doc - директория с документацией проекта
* lst - директория с файлами листов (файлами где указаны пути до исходников проекта)
** files_rtl_svh.lst - файл с относительными путями исходников формата SystemVerilog header (.svh), в них обычно описываются макросы, параметры, интерфейсы, константы.
** files_rtl_verilog.lst - файл с относительными путями до исходников формата System Verilog (.sv)
** files_rtl_vhdl.lst - файл с относительными путями до исходников vhdl
** files_tb_verilog.lst - файл с относительными путями для test bench
** files_mem_lib.lst - файл с АБСОЛЮТНЫМИ путями до .lib исходников памятей
** files_mem_verilog.lst - файл с АБСОЛЮТНЫМИ путями до .v исходников памятей
* sdc - директория для sdc файла, необходимого для синтеза
* src - директория rtl исходников
* syn - директория системы сборки/синтеза.